name: amap_location_fluttify
description: An `Amap` Location Component, Powered By `Fluttify`, A Compiler Generating Dart Bindings For Native SDK.
version: 0.14.0
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/amap_location_fluttify

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
#  amap_core_fluttify: ^0.9.5
#  foundation_fluttify: ^0.8.13-pre.10
#  core_location_fluttify: ^0.2.4
  amap_core_fluttify:
    path: /Users/yohom/Github/Me/All/fluttify/amap/amap_core_fluttify/output-project/amap_core_fluttify

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  foundation_fluttify:
    path: /Users/yohom/Github/Me/All/fluttify/fluttify_infra/foundation_fluttify
  core_location_fluttify:
    path: /Users/yohom/Github/Me/All/fluttify/fluttify_infra/core_location_fluttify

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_location_fluttify
        pluginClass: AmapLocationFluttifyPlugin
      ios:
        pluginClass: AmapLocationFluttifyPlugin